spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/demodata?useSSL=false&serverTimezone=UTC'
    username: 'root'
    password: 'Q17f4r4qMP!'
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
  jpa:
    show-sql: true
    database-platform: 'org.hibernate.dialect.MySQLDialect'
    generate-ddl: true
    hibernate:
      ddl-auto: none
    open-in-view: false
  application:
    name: demodata
